/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  MatchResults,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppAuthentication {

    }
  }

  interface HTMLAppAuthenticationElement extends StencilComponents.AppAuthentication, HTMLStencilElement {}

  var HTMLAppAuthenticationElement: {
    prototype: HTMLAppAuthenticationElement;
    new (): HTMLAppAuthenticationElement;
  };
  interface HTMLElementTagNameMap {
    'app-authentication': HTMLAppAuthenticationElement;
  }
  interface ElementTagNameMap {
    'app-authentication': HTMLAppAuthenticationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-authentication': JSXElements.AppAuthenticationAttributes;
    }
  }
  namespace JSXElements {
    export interface AppAuthenticationAttributes extends HTMLAttributes {
      'onAuthenticationResponse'?: (event: CustomEvent) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHome {
      'uid': string;
    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      'uid'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface DisplayWorkouts {
      'uid': string;
    }
  }

  interface HTMLDisplayWorkoutsElement extends StencilComponents.DisplayWorkouts, HTMLStencilElement {}

  var HTMLDisplayWorkoutsElement: {
    prototype: HTMLDisplayWorkoutsElement;
    new (): HTMLDisplayWorkoutsElement;
  };
  interface HTMLElementTagNameMap {
    'display-workouts': HTMLDisplayWorkoutsElement;
  }
  interface ElementTagNameMap {
    'display-workouts': HTMLDisplayWorkoutsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'display-workouts': JSXElements.DisplayWorkoutsAttributes;
    }
  }
  namespace JSXElements {
    export interface DisplayWorkoutsAttributes extends HTMLAttributes {
      'uid'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface WorkoutsDashboard {
      'uid': string;
    }
  }

  interface HTMLWorkoutsDashboardElement extends StencilComponents.WorkoutsDashboard, HTMLStencilElement {}

  var HTMLWorkoutsDashboardElement: {
    prototype: HTMLWorkoutsDashboardElement;
    new (): HTMLWorkoutsDashboardElement;
  };
  interface HTMLElementTagNameMap {
    'workouts-dashboard': HTMLWorkoutsDashboardElement;
  }
  interface ElementTagNameMap {
    'workouts-dashboard': HTMLWorkoutsDashboardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'workouts-dashboard': JSXElements.WorkoutsDashboardAttributes;
    }
  }
  namespace JSXElements {
    export interface WorkoutsDashboardAttributes extends HTMLAttributes {
      'uid'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
